version: "3.8"

services:
  api:
    build: .
    ports:
      - "3000:3000"
    command: ["/usr/local/bin/api"]
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PORT: ${POSTGRES_PORT}

      REDIS_PORT: ${REDIS_PORT}
      
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS}
      
    depends_on:
      - db
      - redis
      - rabbitmq
    networks:
      - app_network

  # workers:
  #   build: .
  #   command: ["/usr/local/bin/worker"]
  #   depends_on:
  #     - db
  #     - redis
  #     - rabbitmq
  #   networks:
  #     - app_network

  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    networks:
      - app_network

  redis:
    image: redis:latest
    restart: always
    ports:
      - "6379:6379"
    networks:
      - app_network

  rabbitmq:
    image: rabbitmq:3-management
    restart: always
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS}
    ports:
      - "5672:5672"   # Porta para comunicação com aplicações
      - "15672:15672" # Porta para acessar o painel de administração
    networks:
      - app_network

networks:
  app_network:
    driver: bridge
